CREATE DATABASE IF NOT EXISTS dozon_internship
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE dozon_internship;

DROP TABLE IF EXISTS TBL_TUTOR_AVAILABLE_TIME;

CREATE TABLE TBL_TUTOR_AVAILABLE_TIME (
  availabilitySeq INT NOT NULL AUTO_INCREMENT COMMENT '강사 가능시간 고유값',
  tutorId VARCHAR(20) NOT NULL COMMENT '강사 아이디',
  tutorName NVARCHAR(50) NOT NULL COMMENT '강사명',
  dayOfWeek TINYINT NOT NULL COMMENT '요일: 1=월, 2=화, 3=수, 4=목, 5=금',
  slotStartTime TIME NOT NULL COMMENT '가능 시작 시간',
  slotEndTime TIME NOT NULL COMMENT '가능 종료 시간',
  display CHAR(1) NOT NULL DEFAULT '1' COMMENT '사용 여부: 1=사용, 0=미사용',
  regDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  modDate DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
  PRIMARY KEY (availabilitySeq),
  UNIQUE KEY UX_TBL_TUTOR_AVAILABLE_TIME_SLOT (tutorId, dayOfWeek, slotStartTime),
  KEY IX_TBL_TUTOR_AVAILABLE_TIME_TUTOR (tutorId, display),
  KEY IX_TBL_TUTOR_AVAILABLE_TIME_DAY_TIME (dayOfWeek, slotStartTime)
) COMMENT='강사 가능시간';
