CREATE DATABASE IF NOT EXISTS dozon_internship
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE dozon_internship;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS TBL_CLASS_SCHEDULE;
DROP TABLE IF EXISTS TBL_ENROLLMENT_WEEKDAY;
DROP TABLE IF EXISTS TBL_ENROLLMENT;
DROP TABLE IF EXISTS TBL_COURSE;
DROP TABLE IF EXISTS TBL_TUTOR;
DROP TABLE IF EXISTS TBL_STUDENT;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE TBL_STUDENT (
  studentSeq INT NOT NULL AUTO_INCREMENT COMMENT '학생 고유 순번',
  studentId VARCHAR(30) NOT NULL COMMENT '학생 아이디',
  studentNo VARCHAR(20) NOT NULL COMMENT '학생 고유번호',
  studentName VARCHAR(50) NOT NULL COMMENT '학생명',
  studentPhone VARCHAR(20) NULL COMMENT '학생 연락처',
  studentEmail VARCHAR(100) NULL COMMENT '학생 이메일',
  display CHAR(1) NOT NULL DEFAULT '1' COMMENT '사용 여부: 1=사용, 0=미사용',
  regDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  modDate DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
  PRIMARY KEY (studentSeq),
  UNIQUE KEY UX_TBL_STUDENT_ID (studentId),
  UNIQUE KEY UX_TBL_STUDENT_NO (studentNo),
  CONSTRAINT CK_TBL_STUDENT_DISPLAY CHECK (display IN ('0', '1'))
) COMMENT='학생 기본정보';

CREATE TABLE TBL_TUTOR (
  tutorSeq INT NOT NULL AUTO_INCREMENT COMMENT '강사 고유 순번',
  tutorId VARCHAR(30) NOT NULL COMMENT '강사 아이디',
  tutorName VARCHAR(50) NOT NULL COMMENT '강사명',
  tutorPhone VARCHAR(20) NULL COMMENT '강사 연락처',
  tutorEmail VARCHAR(100) NULL COMMENT '강사 이메일',
  display CHAR(1) NOT NULL DEFAULT '1' COMMENT '사용 여부: 1=사용, 0=미사용',
  regDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  modDate DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
  PRIMARY KEY (tutorSeq),
  UNIQUE KEY UX_TBL_TUTOR_ID (tutorId),
  CONSTRAINT CK_TBL_TUTOR_DISPLAY CHECK (display IN ('0', '1'))
) COMMENT='강사 기본정보';

CREATE TABLE TBL_COURSE (
  courseSeq INT NOT NULL AUTO_INCREMENT COMMENT '수업과정 고유 순번',
  courseCode VARCHAR(20) NOT NULL COMMENT '수업과정 코드',
  courseName VARCHAR(100) NOT NULL COMMENT '수업과정명',
  courseLevel VARCHAR(20) NULL COMMENT '과정 레벨',
  courseDescription VARCHAR(500) NULL COMMENT '과정 설명',
  display CHAR(1) NOT NULL DEFAULT '1' COMMENT '사용 여부: 1=사용, 0=미사용',
  regDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  modDate DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
  PRIMARY KEY (courseSeq),
  UNIQUE KEY UX_TBL_COURSE_CODE (courseCode),
  CONSTRAINT CK_TBL_COURSE_DISPLAY CHECK (display IN ('0', '1'))
) COMMENT='수업과정 정보';

CREATE TABLE TBL_ENROLLMENT (
  enrollmentSeq INT NOT NULL AUTO_INCREMENT COMMENT '수강신청 고유 순번',
  enrollmentId VARCHAR(20) NOT NULL COMMENT '수강신청번호',
  studentId VARCHAR(30) NOT NULL COMMENT '학생 아이디',
  courseCode VARCHAR(20) NOT NULL COMMENT '수업과정 코드',
  tutorId VARCHAR(30) NOT NULL COMMENT '강사 아이디',
  lessonStartDate DATE NOT NULL COMMENT '수업 시작일',
  lessonEndDate DATE NOT NULL COMMENT '수업 종료일',
  lessonCount SMALLINT NOT NULL COMMENT '수업횟수',
  lessonStartTime TIME NOT NULL COMMENT '수업 시작시간',
  lessonDurationMinutes SMALLINT NOT NULL COMMENT '수업시간(분)',
  enrollmentStatus TINYINT NOT NULL DEFAULT 1 COMMENT '신청상태: 1=신청, 2=진행중, 3=종료, 9=취소',
  studentRequestDesc VARCHAR(500) NULL COMMENT '학생 요청사항',
  regDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  modDate DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
  PRIMARY KEY (enrollmentSeq),
  UNIQUE KEY UX_TBL_ENROLLMENT_ID (enrollmentId),
  KEY IX_TBL_ENROLLMENT_STUDENT (studentId, enrollmentStatus),
  KEY IX_TBL_ENROLLMENT_TUTOR_TIME (tutorId, lessonStartDate, lessonEndDate, lessonStartTime),
  KEY IX_TBL_ENROLLMENT_COURSE (courseCode),
  CONSTRAINT FK_TBL_ENROLLMENT_STUDENT
    FOREIGN KEY (studentId) REFERENCES TBL_STUDENT (studentId)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_TBL_ENROLLMENT_COURSE
    FOREIGN KEY (courseCode) REFERENCES TBL_COURSE (courseCode)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_TBL_ENROLLMENT_TUTOR
    FOREIGN KEY (tutorId) REFERENCES TBL_TUTOR (tutorId)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT CK_TBL_ENROLLMENT_LESSON_COUNT CHECK (lessonCount > 0),
  CONSTRAINT CK_TBL_ENROLLMENT_DATE_RANGE CHECK (lessonStartDate <= lessonEndDate),
  CONSTRAINT CK_TBL_ENROLLMENT_DURATION CHECK (lessonDurationMinutes > 0),
  CONSTRAINT CK_TBL_ENROLLMENT_STATUS CHECK (enrollmentStatus IN (1, 2, 3, 9))
) COMMENT='수강신청 정보';

CREATE TABLE TBL_ENROLLMENT_WEEKDAY (
  enrollmentWeekdaySeq INT NOT NULL AUTO_INCREMENT COMMENT '수강신청 요일 고유 순번',
  enrollmentSeq INT NOT NULL COMMENT '수강신청 고유 순번',
  dayOfWeek TINYINT NOT NULL COMMENT '수업요일: 0=월, 1=화, 2=수, 3=목, 4=금, 5=토, 6=일',
  regDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (enrollmentWeekdaySeq),
  UNIQUE KEY UX_TBL_ENROLLMENT_WEEKDAY (enrollmentSeq, dayOfWeek),
  KEY IX_TBL_ENROLLMENT_WEEKDAY_DAY (dayOfWeek),
  CONSTRAINT FK_TBL_ENROLLMENT_WEEKDAY_ENROLLMENT
    FOREIGN KEY (enrollmentSeq) REFERENCES TBL_ENROLLMENT (enrollmentSeq)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT CK_TBL_ENROLLMENT_WEEKDAY_DAY CHECK (dayOfWeek BETWEEN 0 AND 6)
) COMMENT='수강신청별 수업요일';

CREATE TABLE TBL_CLASS_SCHEDULE (
  classSeq INT NOT NULL AUTO_INCREMENT COMMENT '일자별 수업 고유 순번',
  classId VARCHAR(30) NOT NULL COMMENT '일자별 수업번호',
  enrollmentSeq INT NOT NULL COMMENT '수강신청 고유 순번',
  lessonRound SMALLINT NOT NULL COMMENT '수업 회차',
  classDate DATE NOT NULL COMMENT '수업일',
  dayOfWeek TINYINT NOT NULL COMMENT '수업요일: 0=월, 1=화, 2=수, 3=목, 4=금, 5=토, 6=일',
  classStartTime TIME NOT NULL COMMENT '수업 시작시간',
  classEndTime TIME NOT NULL COMMENT '수업 종료시간',
  classDurationMinutes SMALLINT NOT NULL COMMENT '수업시간(분)',
  tutorId VARCHAR(30) NOT NULL COMMENT '강사 아이디',
  classStatus TINYINT NOT NULL DEFAULT 1 COMMENT '수업상태: 1=예정, 2=완료, 9=취소',
  classUrl VARCHAR(200) NULL COMMENT '화상수업 URL',
  classMemo VARCHAR(500) NULL COMMENT '수업 메모',
  regDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  modDate DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
  PRIMARY KEY (classSeq),
  UNIQUE KEY UX_TBL_CLASS_SCHEDULE_ID (classId),
  UNIQUE KEY UX_TBL_CLASS_SCHEDULE_ROUND (enrollmentSeq, lessonRound),
  UNIQUE KEY UX_TBL_CLASS_SCHEDULE_TUTOR_START (tutorId, classDate, classStartTime),
  KEY IX_TBL_CLASS_SCHEDULE_DATE (classDate, classStartTime),
  KEY IX_TBL_CLASS_SCHEDULE_ENROLLMENT (enrollmentSeq, classDate),
  CONSTRAINT FK_TBL_CLASS_SCHEDULE_ENROLLMENT
    FOREIGN KEY (enrollmentSeq) REFERENCES TBL_ENROLLMENT (enrollmentSeq)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_TBL_CLASS_SCHEDULE_TUTOR
    FOREIGN KEY (tutorId) REFERENCES TBL_TUTOR (tutorId)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT CK_TBL_CLASS_SCHEDULE_ROUND CHECK (lessonRound > 0),
  CONSTRAINT CK_TBL_CLASS_SCHEDULE_DAY CHECK (dayOfWeek BETWEEN 0 AND 6),
  CONSTRAINT CK_TBL_CLASS_SCHEDULE_DURATION CHECK (classDurationMinutes > 0),
  CONSTRAINT CK_TBL_CLASS_SCHEDULE_TIME CHECK (classStartTime < classEndTime),
  CONSTRAINT CK_TBL_CLASS_SCHEDULE_STATUS CHECK (classStatus IN (1, 2, 9))
) COMMENT='일자별 수업정보';
